#!/bin/bash
### BEGIN INIT INFO
# Provides:				ASCI-120
# Required-Start:		$local_fs $remote_fs $syslog $time
# Required-Stop:		$local_fs $remote_fs $syslog 
# Default-Start:		2 3 4 5
# Default-Stop:			0 1 6
# Short-Description:	INNODISK Linux EApi Starter
# Description:			INNODISK Linux EApi Starter, used for setup eapi setup
### END INIT INFO

### parameter


do_start()
{
    sudo pkill -2 EApi_Test
    sleep 0.2
    sudo rmmod innoeapi
    # sudo insmod /etc/init.d/innoeapi.ko
    sudo modprobe innoeapi

    timeout=60
}

do_stop()
{
    sudo pkill -2 EApi_Test
}

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "eapi: Starting run_eapidriver" > /dev/kmsg
    do_start
    ;;
  stop)
    echo "eapi: Stopping run_eapidriver" > /dev/kmsg
    do_stop
    ;;
  *)
    echo "eapi: Usage: /etc/init.d/blah {start|stop}" > /dev/kmsg
    exit 1
    ;;
esac
 
exit 0