# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestTool2.0_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_meslogin_Dialog(object):
    def setupUi(self, meslogin_Dialog):
        meslogin_Dialog.setObjectName("meslogin_Dialog")
        meslogin_Dialog.resize(800, 600)
        self.SN_label = QtWidgets.QLabel(meslogin_Dialog)
        self.SN_label.setGeometry(QtCore.QRect(500, 230, 191, 31))
        self.SN_label.setObjectName("SN_label")
        self.mes_ent_btn = QtWidgets.QPushButton(meslogin_Dialog)
        self.mes_ent_btn.setGeometry(QtCore.QRect(428, 420, 331, 91))
        self.mes_ent_btn.setObjectName("mes_ent_btn")
        self.Runcard_label = QtWidgets.QLabel(meslogin_Dialog)
        self.Runcard_label.setGeometry(QtCore.QRect(530, 50, 131, 31))
        self.Runcard_label.setObjectName("Runcard_label")
        self.OP_label = QtWidgets.QLabel(meslogin_Dialog)
        self.OP_label.setGeometry(QtCore.QRect(520, 320, 131, 31))
        self.OP_label.setObjectName("OP_label")
        self.WO_label = QtWidgets.QLabel(meslogin_Dialog)
        self.WO_label.setGeometry(QtCore.QRect(520, 140, 171, 31))
        self.WO_label.setObjectName("WO_label")
        self.SN_lineEdit = QtWidgets.QLineEdit(meslogin_Dialog)
        self.SN_lineEdit.setGeometry(QtCore.QRect(410, 260, 361, 25))
        self.SN_lineEdit.setObjectName("SN_lineEdit")
        self.OP_lineEdit = QtWidgets.QLineEdit(meslogin_Dialog)
        self.OP_lineEdit.setGeometry(QtCore.QRect(410, 350, 361, 25))
        self.OP_lineEdit.setObjectName("OP_lineEdit")
        self.WO_lineEdit = QtWidgets.QLineEdit(meslogin_Dialog)
        self.WO_lineEdit.setGeometry(QtCore.QRect(410, 170, 361, 25))
        self.WO_lineEdit.setObjectName("WO_lineEdit")
        self.RunCard_lineEdit = QtWidgets.QLineEdit(meslogin_Dialog)
        self.RunCard_lineEdit.setGeometry(QtCore.QRect(410, 80, 361, 25))
        self.RunCard_lineEdit.setObjectName("RunCard_lineEdit")
        self.MES_textEdit = QtWidgets.QTextEdit(meslogin_Dialog)
        self.MES_textEdit.setGeometry(QtCore.QRect(20, 80, 381, 441))
        self.MES_textEdit.setObjectName("MES_textEdit")
        self.MES_label = QtWidgets.QLabel(meslogin_Dialog)
        self.MES_label.setGeometry(QtCore.QRect(180, 50, 71, 31))
        self.MES_label.setObjectName("MES_label")

        self.retranslateUi(meslogin_Dialog)
        QtCore.QMetaObject.connectSlotsByName(meslogin_Dialog)
        meslogin_Dialog.setTabOrder(self.RunCard_lineEdit, self.WO_lineEdit)
        meslogin_Dialog.setTabOrder(self.WO_lineEdit, self.SN_lineEdit)
        meslogin_Dialog.setTabOrder(self.SN_lineEdit, self.OP_lineEdit)
        meslogin_Dialog.setTabOrder(self.OP_lineEdit, self.mes_ent_btn)

    def retranslateUi(self, meslogin_Dialog):
        _translate = QtCore.QCoreApplication.translate
        meslogin_Dialog.setWindowTitle(_translate("meslogin_Dialog", "主機板測試工具"))
        self.SN_label.setText(_translate("meslogin_Dialog", "安提機台序號(SN) - 限 11碼"))
        self.mes_ent_btn.setText(_translate("meslogin_Dialog", "進站"))
        self.Runcard_label.setText(_translate("meslogin_Dialog", "流程卡號(Runcard)"))
        self.OP_label.setText(_translate("meslogin_Dialog", "人員工號(Operator)"))
        self.WO_label.setText(_translate("meslogin_Dialog", "工單號碼(Work Order)"))
        self.MES_label.setText(_translate("meslogin_Dialog", "MES資訊"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    meslogin_Dialog = QtWidgets.QDialog()
    ui = Ui_meslogin_Dialog()
    ui.setupUi(meslogin_Dialog)
    meslogin_Dialog.show()
    sys.exit(app.exec_())
